version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbotdb
    ports:
      # Eğer 5432 zaten lokalde doluysa soldaki 5432'yi 5433 yap: "5433:5432"
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
